defaults:
  # - algorithm: ppobc # does not matter if phase is bc_pop
  # - nn: lstm
  # - phase: bc_pop
  - policy: policy
  - rollout: rollout 
  - environment: flappy_bird_gym
  - algorithm: bc
  - augmentation: mentalmodel


seed: 0
use_collected_traj: true
