defaults:
  - _self_
name: bc
seed: 0
log_path: ./logs/bc
load_pretrained_policy: true
training_params:
  epochs: 100
  validation_split: 0.15
  batch_size: 64
  learning_rate: 1e-3
  use_class_weights: false
  train_model: true

evaluation_params:
  ep_length: 400
  num_eval_episodes: 10
  display: false
  load_from_ckpt: true