defaults:
  - _self_
name: gail
seed: 0
log_path: ./logs/gail
load_pretrained_policy: true

policy_viz_params:
  save_video_policy: false
  save_video_folder: ./saved_stuff/gail/policy_videos
  fps: 30
  video_log_freq_round: 1
  
rl_training_params:
  epochs: 5
  batch_size: 64
  learning_rate: 0.00005
  use_class_weights: false
  train_model: true
  ent_coef: 0.2
  gamma: 0.95
  gen_train_timesteps: null

training_params:
  total_timesteps: 400000
  batch_size: 1024
  gen_replay_buffer_capacity: 512
  n_disc_updates_per_round: 8

evaluation_params:
  ep_length: 400
  num_eval_episodes: 5
  display: false
  load_from_ckpt: true