# environment:
# Config can be improved later, but for now to get the code running, not splitting the configs into different types
level: "full-divider_salad"
num_agents: 2
max_num_timesteps: 100
max_num_subtasks: 14
seed: 1
with_image_obs: false
play: false
record: false
render: false

# delegation_planner:
beta: 1.3

# navigation_planner:
alpha: 0.01
tau: 2
cap: 75
main_cap: 100

# models:
model1: "greedy"
model2: "greedy"
model3: null
model4: null
